# SendMessageFailureReason

The reason for a failure to send an Inbox message:
  * `CONFLICTING_SOURCE_ID`: A message with the same `MessageSourceId` already exists.
  * `UNKNOWN`: The message failed to send due to an unknown conflict.


| **Value** |
| --------- |
| `"CONFLICTING_SOURCE_ID"` |
| `"UNKNOWN"` |


[[Back to Model list]](../../../../README.md#models-v1-link) [[Back to API list]](../../../../README.md#apis-v1-link) [[Back to README]](../../../../README.md)
